###
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "dani",
    "email": "dani@gmail.com",
    "password": "dani"
}


###
GET http://localhost:3000/users HTTP/1.1


###
GET http://localhost:3000/api/users/666dd499f7aebb9896e20bca HTTP/1.1


###
PUT http://localhost:3000/api/users/666dd499f7aebb9896e20bca HTTP/1.1
Content-Type: application/json

{
    "name": "NADSSAD",
    "age": "4243",
    "email": "danidasfel.alvarado@ucr.ac.c2r"
}

###
DELETE http://localhost:3000/api/users/666dce263da5a14f99e0b1b7 HTTP/1.1


### //VER TODOS LOS USUARIOS (NO TIENE AUTH)
GET http://localhost:3000/api/users



### //LOGEARME
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "hola@gmail.com",
    "password": "123"
}

### //LA RESPONSE EJECUTADA CON EL TOKEN DEL LOGIN PARA TRAERME A UN USUARIO
GET http://localhost:3000/api/users/user/666fb0de3406c14497446dc0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjZmYjBkZTM0MDZjMTQ0OTc0NDZkYzAiLCJpYXQiOjE3MTg5ODg2OTcsImV4cCI6MTcxODk4ODc1N30.55zNizPskU_33Q6wnvHPjpAjaPwkJJ-WZ5cumluNpg8
