###
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "country": "México",
    "email": "alvaradodaniel128@gmail.com",
    "password": "12345",
    "image": "user.png",
    "role": "admin",
    "achievements": [
      {
        "id_achievement": "12345"
      }
    ],
    "comments": [
      {
        "type": "Suggestion",
        "description": "Es una pagina a la que le falta..."
      }
    ],
    "name": "Daniel Alvarado"
  }

  ###
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "country": "México",
    "email": "alvaradodaniel128@gmail.com",
    "password": "12345",
    "image": "user.png",
    "role": "admin",
    "achievements": [
      {
        "id_achievement": "12345"
      }
    ],
    "comments": [
      {
        "type": "Suggestion",
        "description": "Es una pagina a la que le falta..."
      }
    ],
    "name": "Daniel Alvarado"
  }



###
GET http://localhost:3000/users HTTP/1.1


###
GET http://localhost:3000/api/users/667c6aba6f7d23af59ac11c3 HTTP/1.1


###
PUT http://localhost:3000/api/users/666dd499f7aebb9896e20bca HTTP/1.1
Content-Type: application/json

{
    "name": "NADSSAD",
    "age": "4243",
    "email": "danidasfel.alvarado@ucr.ac.c2r"
}

###
DELETE http://localhost:3000/api/users/666dce263da5a14f99e0b1b7 HTTP/1.1


### //VER TODOS LOS USUARIOS (NO TIENE AUTH)
GET http://localhost:3000/api/users



### //LOGEARME
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "alvaradodaniel128@gmail.com",
    "password": "12345"
}

### //LA RESPONSE EJECUTADA CON EL TOKEN DEL LOGIN PARA TRAERME A UN USUARIO
GET http://localhost:3000/api/users/user/666f92553c47469784455e8e
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjdjNmFiYTZmN2QyM2FmNTlhYzExYzMiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTk0Mjk4NDcsImV4cCI6MTcxOTQzMzQ0N30.7BX6WdXuqsIF9d9Rx5mw8hEXVkjky5ehSw1TotK9bqk



### //LA RESPONSE EJECUTADA CON EL TOKEN DEL LOGIN PARA TRAERME A UN USUARIO
GET http://localhost:3000/  



### //LA RESPONSE EJECUTADA CON EL TOKEN DEL LOGIN PARA TRAERME A UN USUARIO
POST http://localhost:3000/api/users/checkuser
Content-Type: application/json

{
    "email": "alvaradodaniel128@gmail.com",
    "password": "12345"
  }



### //LA RESPONSE EJECUTADA CON EL TOKEN DEL LOGIN PARA TRAERME A UN USUARIO
GET http://localhost:3000/api/locations/events

### //LA RESPONSE EJECUTADA CON EL TOKEN DEL LOGIN PARA TRAERME A UN USUARIO
GET http://localhost:3000/api/locations/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjdjNmFiYTZmN2QyM2FmNTlhYzExYzMiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTk3MjU3NzEsImV4cCI6MTcxOTcyOTM3MX0.e2USwkIMlZCbir57P7w3CA2yxItF2pGT1afeGt5JjYc

### //LA RESPONSE EJECUTADA CON EL TOKEN DEL LOGIN PARA TRAERME A UN USUARIO
GET http://localhost:3000/api/locations/historical/666f90583c47469784455e85
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjdjNmFiYTZmN2QyM2FmNTlhYzExYzMiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTk3OTAxMzcsImV4cCI6MTcxOTc5MzczN30.dUugktgRA0fVh88GFdinxuHt-QQkDavlR8H-Q3kDLAQ  

### //LA RESPONSE EJECUTADA CON EL TOKEN DEL LOGIN PARA TRAERME A UN USUARIO
GET http://localhost:3000/api/users/getAchievements/667c6aba6f7d23af59ac11c3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjdjNmFiYTZmN2QyM2FmNTlhYzExYzMiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjAyODkzNDEsImV4cCI6MTcyMDI5Mjk0MX0.iwfNEGa3iWr5X7CfSanIXvKDhawVjNyFkYqrHC8WcyE

###
GET http://localhost:3000/api/users/admin/getcomments
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjdjNmFiYTZmN2QyM2FmNTlhYzExYzMiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjAyODkzNDEsImV4cCI6MTcyMDI5Mjk0MX0.iwfNEGa3iWr5X7CfSanIXvKDhawVjNyFkYqrHC8WcyE


###
POST http://localhost:3000/api/locations/addlocation
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjdjNmFiYTZmN2QyM2FmNTlhYzExYzMiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjAzMDY0ODMsImV4cCI6MTcyMDMxMDA4M30.82FvffThYYtSKkgaUO4xIn8dn-SpFM3GT5inX92lAmE
Content-Type: application/json

{
  "name": "Mi casa",
  "coordinate": "28.60392954475209, -106.01714628253514",
  "description": "hola",
  "year" : "2004",
  "urlvideo" : "urlhistoricalyt",
  "image" : "fja.jpg",
  "pintype": "historical",
  "loctype": "Lugar historica",
  "model": "fdasdf.glb"
}


###
GET http://localhost:3000/api/users/mymodels/667c6aba6f7d23af59ac11c3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjdjNmFiYTZmN2QyM2FmNTlhYzExYzMiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjAzMzc3MTMsImV4cCI6MTcyMDM0MTMxM30.sLFjjzdMCQ10lc7DZ6i2h7SKTm7l1ibhJguZKisnjzk


###
GET http://localhost:3000/api/locations/questions/666f90583c47469784455e87
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjdjNmFiYTZmN2QyM2FmNTlhYzExYzMiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjI0NjgxNTMsImV4cCI6MTcyMjQ3MTc1M30.GfGVMGvfVO8aQXw6Ndy9ugSf2CVTirEi0j3zi6ACCQc

###
POST http://localhost:3000/api/users/giveAchievement/667c6aba6f7d23af59ac11c3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjdjNmFiYTZmN2QyM2FmNTlhYzExYzMiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjExNTk3NDgsImV4cCI6MTcyMTE2MzM0OH0.p-IizFf75f5uNr7lOvQXpQu7pyCJ1_w7f1g10KrXWh4
Content-Type: application/json

{
  "id_achievement": "66944d9ca9723bd7b1a7541d"
}

###
GET http://localhost:3001/api/locations/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjdjNmFiYTZmN2QyM2FmNTlhYzExYzMiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MjEzNDk2NTYsImV4cCI6MTcyMTM1MzI1Nn0.SqypOdSWC3gshb21eb_6xJsShBQIfB33UFGYgSrDwxY


###
POST http://localhost:3000/api/users/unlockmodel
Content-Type: application/json

{
  "id_card":"B61C6E80",
  "id_module":"8932D90"
}